/*
 * This file was auto-generated by the config-tool of fpga-log.
 * Do not change this file!
 */

#ifndef PERIPHERALS_SIM_H_
#define PERIPHERALS_SIM_H_

#define PIPE_COUNT 3

#define TIMER_COUNT 1
#define COMPARE_COUNT 1

#define DEVICE_HCT99_0_UART_LIGHT 0
#define DEVICE_PWM_0_PWM_REGS 1
#define DM_TIMER_0_TIMER_REGS 0
#define DM_TIMER_0_COMPARE_REGS 0
#define SINK_SD_CARD_0_SD_CARD "/dev/sde"
#define SINK_UART_0_UART_LIGHT 2

#define TIMESTAMP_CAPTURE_SIGNALS_COUNT 1
#define TIMESTAMP_CAPTURE_SIGNALS {DEVICE_HCT99_0_UART_LIGHT}

#endif
