/*
 * This file was auto-generated by the config-tool of fpga-log.
 * Do not change this file!
 */

#include "logger_config.h"
#include <system/peripherals.h>
#include <fpga-log/pc_compatibility.h>
#include <fpga-log/control_port.h>

#include <fpga-log/device/device_hct99.h>
#include <fpga-log/device/device_pwm.h>
#include <fpga-log/dm/control_action_simple.h>
#include <fpga-log/dm/datastream_condition_compare_float.h>
#include <fpga-log/dm/datastream_condition_compare_val_name.h>
#include <fpga-log/dm/dm_filter.h>
#include <fpga-log/dm/dm_splitter_data.h>
#include <fpga-log/dm/dm_timer.h>
#include <fpga-log/dm/dm_trigger.h>
#include <fpga-log/simple_float.h>
#include <fpga-log/sink/control_protocol_ascii.h>
#include <fpga-log/sink/formatter/formatter_simple.h>
#include <fpga-log/sink/sink_sd_card.h>
#include <fpga-log/sink/sink_uart.h>

control_action_simple_t	control_action_simple_0;
control_action_simple_t	control_action_simple_1;
control_protocol_ascii_t	control_protocol_ascii_0;
datastream_condition_compare_float_t	datastream_condition_compare_float_0;
datastream_condition_compare_val_name_t	datastream_condition_compare_val_name_0;
device_hct99_t	device_hct99_0;
device_pwm_t	device_pwm_0;
dm_filter_t	dm_filter_0;
dm_splitter_data_t	dm_splitter_data_0;
dm_timer_t	dm_timer_0;
dm_trigger_t	dm_trigger_0;
formatter_simple_t	formatter_simple_0;
formatter_simple_t	formatter_simple_1;
simple_float_b10_t	simple_float_b10_0;
sink_sd_card_t	sink_sd_card_0;
sink_uart_t	sink_uart_0;

void init_objects(void) {
  control_action_simple_init(&control_action_simple_0);
  control_action_simple_init(&control_action_simple_1);
  control_protocol_ascii_init(&control_protocol_ascii_0);
  simple_float_b10_init(&simple_float_b10_0, 30000, 3);
  datastream_condition_compare_float_init(&datastream_condition_compare_float_0, greater_float, simple_float_b10_0);
  datastream_condition_compare_val_name_init(&datastream_condition_compare_val_name_0, RESULT_MODE_EQUAL, "Tc");
  device_hct99_init(&device_hct99_0, DEVICE_HCT99_0_UART_LIGHT, 1);
  device_pwm_init(&device_pwm_0, DEVICE_PWM_0_PWM_REGS);
  dm_filter_init(&dm_filter_0, FILTER_MODE_PASS, &datastream_condition_compare_val_name_0);
  dm_splitter_data_init(&dm_splitter_data_0);
  dm_timer_init(&dm_timer_0, 1000, &control_action_simple_0, DM_TIMER_0_TIMER_REGS, DM_TIMER_0_COMPARE_REGS);
  dm_trigger_init(&dm_trigger_0, &control_action_simple_1);
  formatter_simple_init(&formatter_simple_0);
  formatter_simple_init(&formatter_simple_1);
  sink_sd_card_init(&sink_sd_card_0, &formatter_simple_1, SINK_SD_CARD_0_SD_CARD);
  sink_uart_init(&sink_uart_0, &formatter_simple_0, &control_protocol_ascii_0, SINK_UART_0_UART_LIGHT);
}

void connect_ports(void) {
  sink_uart_add_control_out(&sink_uart_0, device_pwm_get_control_in(&device_pwm_0));
  device_hct99_set_data_out(&device_hct99_0, dm_splitter_data_get_data_in(&dm_splitter_data_0));
  device_hct99_set_error_out(&device_hct99_0, dm_splitter_data_get_data_in(&dm_splitter_data_0));
  device_hct99_set_misc_out(&device_hct99_0, dm_splitter_data_get_data_in(&dm_splitter_data_0));
  dm_trigger_set_control_out(&dm_trigger_0, device_hct99_get_control_in(&device_hct99_0));
  dm_filter_set_data_out(&dm_filter_0, dm_trigger_get_data_in(&dm_trigger_0));
  dm_splitter_data_add_data_out(&dm_splitter_data_0, sink_sd_card_get_data_in(&sink_sd_card_0));
  dm_splitter_data_add_data_out(&dm_splitter_data_0, sink_uart_get_data_in(&sink_uart_0));
  dm_splitter_data_add_data_out(&dm_splitter_data_0, dm_filter_get_data_in(&dm_filter_0));
  dm_timer_set_control_out(&dm_timer_0, device_hct99_get_control_in(&device_hct99_0));
}

void advanced_config(void) {
  control_action_simple_add_paramter_exp(&control_action_simple_0, HCT99_COMMAND_MEASURE_COLOR_VALUE, 0);
  control_action_simple_add_paramter_exp(&control_action_simple_0, PARAMETER_x, 1);
  control_action_simple_add_paramter_exp(&control_action_simple_0, PARAMETER_y, 6);
  control_action_simple_add_paramter_exp(&control_action_simple_1, HCT99_COMMAND_MEASURE_COLOR_VALUE, 0);
  control_action_simple_add_paramter_exp(&control_action_simple_1, PARAMETER_x, 0);
  control_action_simple_add_paramter_exp(&control_action_simple_1, PARAMETER_y, 1);
  control_action_simple_add_command(&control_action_simple_1);
  control_action_simple_add_paramter_exp(&control_action_simple_1, HCT99_COMMAND_MEASURE_COLOR_VALUE, 0);
  control_action_simple_add_paramter_exp(&control_action_simple_1, PARAMETER_x, 0);
  control_action_simple_add_paramter_exp(&control_action_simple_1, PARAMETER_y, 2);
  dm_trigger_set_condition(&dm_trigger_0, &datastream_condition_compare_float_0);
}
